### ISSUE TITLE
Otomi destroy get stuck at the middle of destroying process

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#568] opened 2021-09-01 15:35 UTC
**Describe the bug:**
`otomi destroy` get stuck after uninstalling some of the apps. 

**To Reproduce**
Install otomi chart then destroy the otomi by cli

This is the output of the `helm list -aA` while `otomi destroy` is stuck: 
```
╰─ helm list -aA
NAME                       	NAMESPACE        	REVISION	UPDATED                                	STATUS      	CHART                            	APP VERSION
gatekeeper-artifacts       	gatekeeper-system	1       	2021-08-31 16:58:17.09758404 +0000 UTC 	deployed    	gatekeeper-artifacts-v0.1.0
gatekeeper-operator        	default          	1       	2021-08-31 16:56:16.893266962 +0000 UTC	deployed    	gatekeeper-v3.2.2                	v3.2.2
istio-operator             	default          	1       	2021-08-31 16:58:17.085693438 +0000 UTC	deployed    	istio-operator-1.10.1
istio-operator-artifacts   	istio-operator   	1       	2021-08-31 16:59:51.176574796 +0000 UTC	uninstalling	raw-0.2.3                        	0.2.3
jobs-artifacts             	maintenance      	1       	2021-08-31 16:57:58.366430538 +0000 UTC	deployed    	raw-0.2.3                        	0.2.3
keycloak                   	keycloak         	1       	2021-08-31 16:58:17.081560422 +0000 UTC	deployed    	keycloak-8.2.2                   	10.0.0
knative-init               	default          	1       	2021-08-31 16:57:58.349893379 +0000 UTC	deployed    	knative-init-0.1.0               	1.0
kubernetes-external-secrets	vault            	1       	2021-08-31 16:59:51.18366203 +0000 UTC 	uninstalling	kubernetes-external-secrets-6.1.0	6.1.0
loki-artifacts             	monitoring       	1       	2021-08-31 16:57:58.372197133 +0000 UTC	deployed    	raw-0.2.3                        	0.2.3
otomi                      	default          	1       	2021-08-31 18:56:03.33501 +0200 CEST   	deployed    	otomi-0.2.1                      	APP_VERSION_PLACEHOLDER
vault-operator             	vault            	1       	2021-08-31 16:57:58.906312285 +0000 UTC	deployed    	vault-operator-1.11.0            	1.11.0
vault-operator-artifacts   	vault            	1       	2021-08-31 16:58:17.064268317 +0000 UTC	deployed    	raw-0.2.3                        	0.2.3
```

**Comment by mojtabaimani** [comment] 2021-09-01 18:27
got stuck in otomi destroy again, even after recreating the cluster.
this is the helm list now:
```
Every 2.0s: helm list -aA                                                                                                                             Mojtabas-MacBook-Pro.local: Wed Sep  1 20:27:37 2021

NAME                            NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
cluster-overprovisioner         overprovisioner         1               2021-09-01 17:02:13.936170659 +0000 UTC uninstalling    cluster-overprovisioner-0.4.2           1.0
gatekeeper-artifacts            gatekeeper-system       1               2021-09-01 17:00:03.37300439 +0000 UTC  deployed        gatekeeper-artifacts-v0.1.0
gatekeeper-operator             default                 1               2021-09-01 16:58:09.675450177 +0000 UTC deployed        gatekeeper-v3.2.2                       v3.2.2
istio-operator                  default                 1               2021-09-01 17:00:05.597756999 +0000 UTC deployed        istio-operator-1.10.1
istio-operator-artifacts        istio-operator          1               2021-09-01 17:01:58.146047416 +0000 UTC deployed        raw-0.2.3                               0.2.3
jobs-artifacts                  maintenance             1               2021-09-01 16:59:40.16107364 +0000 UTC  deployed        raw-0.2.3                               0.2.3
keycloak                        keycloak                2               2021-09-01 17:57:07.351142806 +0000 UTC deployed        keycloak-8.2.2                          10.0.0
knative-init                    default                 1               2021-09-01 16:59:40.17105261 +0000 UTC  deployed        knative-init-0.1.0                      1.0
kube-descheduler                kube-system             1               2021-09-01 17:02:13.843326205 +0000 UTC uninstalling    descheduler-helm-chart-0.19.0           0.19.0
kubernetes-external-secrets     vault                   1               2021-09-01 17:02:00.252227629 +0000 UTC deployed        kubernetes-external-secrets-6.1.0       6.1.0
loki-artifacts                  monitoring              2               2021-09-01 17:56:58.79492209 +0000 UTC  deployed        raw-0.2.3                               0.2.3
metrics-server                  kube-system             1               2021-09-01 17:02:13.734421315 +0000 UTC uninstalling    metrics-server-5.8.7                    0.4.4
prometheus-operator             monitoring              2               2021-09-01 17:57:14.582815281 +0000 UTC uninstalling    prometheus-operator-9.3.1               0.38.1
vault-operator                  vault                   1               2021-09-01 16:59:42.96473312 +0000 UTC  deployed        vault-operator-1.11.0                   1.11.0
vault-operator-artifacts        vault                   2               2021-09-01 17:57:07.124349471 +0000 UTC deployed        raw-0.2.3                               0.2.3
```

**Comment by mojtabaimani** [comment] 2021-09-01 18:40
The only way I could stop the process was restarting the docker engine. Then I saw this error message: 
```
ERRO[1083] error waiting for container: invalid character 'u' looking for beginning of value 
```

**Comment by mojtabaimani** [comment] 2021-09-01 18:48
after two failed try with `binzx/otomi destroy`, I tried the old cli `bin/otomi destroy` and it destroyed the whole otomi successfully.

**Comment by Dunky13** [comment] 2021-09-02 08:01
Weird, I just ran `binzx/otomi destroy -vvv` without issue uninstalled all (except otomi chart job)

**Comment by j-zimnowoda** [comment] 2021-09-06 11:52
I could also reproduce that error. 
To me it looks like Kubectl credentials expires and otomi CLI is not able to refresh them.

It is a known issue that we have never been able to solve properly, because refreshing token means using 3rd part CLI like (aws/gcp/az) that are called by Kubectl under the hood.

**Comment by Morriz** [comment] 2021-09-09 13:59
closing as non related to core

**Closed by Morriz** 2021-09-09 13:59 UTC
Labels: bug
