### ISSUE TITLE
Alertmanager stays in CrashLoopBackOff when installing with chart

### ISSUE THREAD

**Issue by srodenhuis** [redkubes/otomi-core#471] opened 2021-07-18 11:43 UTC
When deploying Otomi with Chart, Alertmanager stays in CrashLoopBackOff with the following message:

level=info ts=2021-07-18T11:35:03.013Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.22.2, branch=HEAD, revisi │
│ on=44f8adc06af5101ad64bd8b9c8b18273f2922051)"                                                                                       │
│ level=info ts=2021-07-18T11:35:03.013Z caller=main.go:222 build_context="(go=go1.16.4, user=root@b595c7f32520, date=20210602-07:50: │
│ 37)"                                                                                                                                │
│ level=warn ts=2021-07-18T11:35:03.254Z caller=cluster.go:251 component=cluster msg="failed to join cluster" err="1 error occurred:\ │
│ n\t* Failed to resolve alertmanager-po-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-po-alertmanage │
│ r-0.alertmanager-operated.monitoring.svc on 10.0.0.10:53: no such host\n\n"                                                         │
│ level=info ts=2021-07-18T11:35:03.254Z caller=cluster.go:253 component=cluster msg="will retry joining cluster every 10s"           │
│ level=warn ts=2021-07-18T11:35:03.254Z caller=main.go:312 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to re │
│ solve alertmanager-po-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-po-alertmanager-0.alertmanager- │
│ operated.monitoring.svc on 10.0.0.10:53: no such host\n\n"                                                                          │
│ level=info ts=2021-07-18T11:35:03.254Z caller=cluster.go:671 component=cluster msg="Waiting for gossip to settle..." interval=2s    │
│ level=info ts=2021-07-18T11:35:03.304Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=/etc │
│ /alertmanager/config/alertmanager.yaml                                                                                              │
│ level=error ts=2021-07-18T11:35:03.305Z caller=coordinator.go:118 component=configuration msg="Loading configuration file failed" f │
│ ile=/etc/alertmanager/config/alertmanager.yaml err="unsupported scheme \"\" for URL"                                                │
│ level=info ts=2021-07-18T11:35:03.305Z caller=cluster.go:680 component=cluster msg="gossip not settled but continuing anyway" polls │
│ =0 elapsed=51.364921ms

**Comment by svatwork** [comment] 2021-07-20 06:11
If you post the output like this it is hard to read and difficult to make sense of. 

I would recommend to make a screenshot with the original command, plus steps to reproduce (e.g. a link to the chart used for example so we can see the start-up options).

**Comment by Dunky13** [comment] 2021-07-20 07:52
Closing this issue, due to #472 being the same, but with more context and formatted error log

**Closed by Dunky13** 2021-07-20 07:52 UTC
