### ISSUE TITLE
otomi-values: errors out of the box

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#220] opened 2020-11-30 10:21 UTC
**Describe the bug:** (a clear and concise description of what the bug is)

After setting otomi-values/env/clusters.yaml and otomi-values/env/clouds/aws/dev/* and would like to validate my templates and values, I receive a couple of errors.

**To Reproduce**
1. 

```
mkdir otomi-values && cd $_ && git init .
docker run -e ENV_DIR=$PWD -v $PWD:$PWD otomi/core:latest bin/bootstrap.sh
. bin/aliases
```

2. Set otomi-values/env/clusters.yaml (CLOUD=aws && CLUSTER=dev) and otomi-values/env/clouds/aws/dev/*:

(used '-' to distort the actual values)

clusters.yaml:
```
clouds:
    aws:
        domain: -----
        clusters:
            dev:
                enabled: true
                apiName: arn:aws:eks:------:----------:cluster/------
                apiServer: -----.gr7.-----.eks.amazonaws.com
                k8sVersion: '1.1-'
                otomiVersion: 'master'
                region: ------
```

otomi-values/env/clouds/aws/dev/.env
```
export K8S_CONTEXT="-------------" # equal to ~/.kube/config
```

3. 

Error 1:
```
VERBOSE=1 otomi validate-templates && otomi validate-values
CWD: 0-11-40
bin/otomi: line 355: [: !=: unary operator expected
Info: The 'secrets.*.yaml files' are not decrypted, because /Users/sebastiaanverbeek/Projects/redkubes/test/0-11-40/.sops.yaml file is not present
has_docker=1
ENV_DIR=/Users/sebastiaanverbeek/Projects/redkubes/test/0-11-40
stack_dir=/home/app/stack
helm_config=/Users/sebastiaanverbeek/Library/Preferences/helm
cmd_image=otomi/core:master
check_kube_context=1
K8S_CONTEXT=-----------
IN_DOCKER=
command=bin/validate-templates.sh
Running dockerized version of command: bin/validate-templates.sh
Generating Kubernetes v1.18.0 Manifests for aws-dev.
helmfile-init.yaml: basePath=.
in helmfile.tpl/helmfile-init.yaml: failed to render values files "../values/k8s/k8s-raw.gotmpl": failed to render [../values/k8s/k8s-raw.gotmpl], because of template: stringTemplate:15:34: executing "stringTemplate" at <$team.clusters>: map has no entry for key "clusters"
Validation Failed
```

Error 2:
.vscode/values-schema.yaml:

```
See screenshots; can't copy multiple problems in vscode (#25290). 
```

**Expected behavior:** (a clear and concise description of what you expected to happen)

I expect the first run to go smoothly and without errors. 

**Screenshots:** (if applicable, add screenshots to help explain your problem)

![Screenshot 2020-11-30 at 10.30.12.png](https://images.zenhubusercontent.com/5fb3eb135472cfeda30e7684/91f26d7e-e02c-4a3e-8188-690c5be99cfd)

![Screenshot 2020-11-30 at 10.30.26.png](https://images.zenhubusercontent.com/5fb3eb135472cfeda30e7684/fce27d92-7965-405c-8d4d-5b44e9dc28e5)

**Cluster(s):**
 - Cloud: aws
 - Cluster: dev

**Versions:** (seen in console's `/settings`)
 - Core Version [e.g. 0.11.45?]
 - Console Version: ?
 - API version: ?

**Desktop:** (if relevant)
 - OS: MacOS 
 - Browser: -
 - Version: 10.14.6

**Additional context:** (add any other context about the problem here)

**Comment by Morriz** [comment] 2020-11-30 12:43
Problem is not present in latest master. Closing

**Comment by svatwork** [comment] 2020-11-30 12:50
I pulled the latest image and receive the following problems, I think it's less than before:

![Screenshot 2020-11-30 at 13 48 07](https://user-images.githubusercontent.com/20700197/100612242-f5ba7e80-3312-11eb-9353-e683c99e1843.png)

Any ideas?

**Comment by rawc0der** [comment] 2020-11-30 13:27
I also confirm there are some faulty values, for example on AZURE-DEV environment I see templating is broken. Almost like the secret values are not decrypted and merged in the final output. 
I don't understand if helm-secrets is called on time, here I see the rendering error before helm-secrets logs.

```
Generating manifests for azure-dev cluster.
helmfile-03.init.yaml: basePath=.
in helmfile.d/helmfile-20.ingress.yaml: 3 errors:
err 0: failed to render values files "../values/cert-manager/cert-manager-raw.gotmpl": failed to render [../values/cert-manager/cert-manager-raw.gotmpl], because of template: stringTemplate:8:16: executing "stringTemplate" at <$cm.provider.azure.azuredns>: map has no entry for key "azure"
err 1: failed to render values files "../values/external-dns/external-dns.gotmpl": failed to render [../values/external-dns/external-dns.gotmpl], because of template: stringTemplate:21:10: executing "stringTemplate" at <$dns.azure>: map has no entry for key "azure"
err 2: failed to render values files "../values/ingress-azure/ingress-azure.gotmpl": failed to render [../values/ingress-azure/ingress-azure.gotmpl], because of template: stringTemplate:17:19: executing "stringTemplate" at <$i.armAuth.secretJSON>: map has no entry for key "armAuth"
helmfile-init.yaml: basePath=.
Decrypting secret /Users/alinspinu/Documents/RawDataLabs/RedKubes/GitHub/otomi-core/env/env/charts/secrets.prometheus-operator.yaml
Decrypting secret /Users/alinspinu/Documents/RawDataLabs/RedKubes/GitHub/otomi-core/env/env/clouds/azure/secrets.overrides.azure.yaml
Decrypting secret /Users/alinspinu/Documents/RawDataLabs/RedKubes/GitHub/otomi-core/env/env/teams/secrets.otomi.yaml
Decrypting secret /Users/alinspinu/Documents/RawDataLabs/RedKubes/GitHub/otomi-core/env/env/charts/secrets.drone.yaml
Decrypting secret /Users/alinspinu/Documents/RawDataLabs/RedKubes/GitHub/otomi-core/env/env/teams/secrets.dev.yaml
```

**Comment by Morriz** [comment] 2020-11-30 14:00
> I also confirm there are some faulty values, for example on AZURE-DEV environment I see templating is broken. Almost like the secret values are not decrypted and merged in the final output.
> I don't understand if helm-secrets is called on time, here I see the rendering error before helm-secrets logs.
> 

This issue is about installing demo values, so please report bugs separately if they are unrelated.

**Comment by Morriz** [comment] 2020-11-30 14:01
I can't reproduce this with `otomi/core:latest`, so please state the steps if they are different from the ones above. Otherwise I have to close it

**Comment by Morriz** [comment] 2020-11-30 14:02
> I pulled the latest image and receive the following problems, I think it's less than before:
> 
> ![Screenshot 2020-11-30 at 13 48 07](https://user-images.githubusercontent.com/20700197/100612242-f5ba7e80-3312-11eb-9353-e683c99e1843.png)
> 
> Any ideas?

I hope you do understand that the "Problems" tab reports all kinds of issues, but none of the above refer to our setup. Check the output

**Comment by Morriz** [comment] 2020-11-30 14:04
If you want to turn on extensions globally @svatwork then understand they might say all kinds of things, but they might not concern us. All of our repos contain all their needed extensions, therefor I strongly suggest to NOT turn extensions on globally.

**Comment by svatwork** [comment] 2020-12-01 10:33
> > I pulled the latest image and receive the following problems, I think it's less than before:
> > ![Screenshot 2020-11-30 at 13 48 07](https://user-images.githubusercontent.com/20700197/100612242-f5ba7e80-3312-11eb-9353-e683c99e1843.png)
> > Any ideas?
> 
> I hope you do understand that the "Problems" tab reports all kinds of issues, but none of the above refer to our setup. Check the output

Well I'm assuming it does, because it's part of the recommendations in otomi-core:

```
"streetsidesoftware.code-spell-checker",
```

Anyway, it was complaining about a lot of things in otomi-values but I haven't seen any in otomi-core so YMMV. Furthermore, 
```
"yaml.schemas": {
    ".vscode/values-schema.yaml": "env/*.yaml"
  }
``` 

settings.json is complaining about it's own schema in my otomi-values repository. 

> If you want to turn on extensions globally @svatwork then understand they might say all kinds of things, but they might not concern us. All of our repos contain all their needed extensions, therefor I strongly suggest to NOT turn extensions on globally.

Yes, so you suggest disabling code-spell-checker. Just to be sure: for otomi-core it's a valid recommendation?

```

**Comment by Morriz** [comment] 2020-12-02 10:31
> Well I'm assuming it does, because it's part of the recommendations in otomi-core:
> 
> ```
> "streetsidesoftware.code-spell-checker",
> ```
> 
> Anyway, it was complaining about a lot of things in otomi-values but I haven't seen any in otomi-core so YMMV. 

Indeed. You seemingly have these issue in `otomi-values` repo though, and the plugin should not be active there.
In otomi-core you can do `npm run spellcheck` and see no errors.

> Furthermore,
> 
> ```
> "yaml.schemas": {
>     ".vscode/values-schema.yaml": "env/*.yaml"
>   }
> ```
> 
> settings.json is complaining about it's own schema in my otomi-values repository.

report a bug with the yaml validation authors? I belive it's the redhad yaml plugin.

> 
> > If you want to turn on extensions globally @svatwork then understand they might say all kinds of things, but they might not concern us. All of our repos contain all their needed extensions, therefor I strongly suggest to NOT turn extensions on globally.
> 
> Yes, so you suggest disabling code-spell-checker. Just to be sure: for otomi-core it's a valid recommendation?

Globally, yes. The settings in the repos activate them just for the repo.

**Closed by Morriz** 2020-12-02 10:31 UTC
Labels: bug
