### ISSUE TITLE
The otomi apply command logs helmfile output as errors

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#514] opened 2021-08-11 14:15 UTC
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. run `otomi apply`
2. Observe that `otomi:apply:error ` logs lines that shall be just info
```
│ 2021-08-11T14:11:47.427Z otomi:apply:log Comparing release=team-ns-admin, chart=../charts/team-ns                                                                                                                                          │
│ 2021-08-11T14:11:52.198Z otomi:apply:log Comparing release=job-keycloak, chart=../charts/jobs                                                                                                                                              │
│ 2021-08-11T14:12:00.247Z otomi:apply:log Comparing release=cert-manager-artifacts, chart=../charts/raw                                                                                                                                     │
│ Comparing release=external-dns, chart=../charts/external-dns                                                                                                                                                                               │
│ Comparing release=nginx-ingress, chart=../charts/nginx-ingress                                                                                                                                                                             │
│ 2021-08-11T14:12:00.247Z otomi:apply:error Listing releases matching ^aws-alb-ingress-controller$                                                                                                                                          │
│ 2021-08-11T14:12:00.367Z otomi:apply:error Listing releases matching ^aws-alb-ingress-controller-artifacts$                                                                                                                                │
│ 2021-08-11T14:12:00.465Z otomi:apply:error Listing releases matching ^ingress-azure$                                                                                                                                                       │
│ 2021-08-11T14:12:00.566Z otomi:apply:error Listing releases matching ^ingress-merge$                                                                                                                                                       │
│ 2021-08-11T14:12:00.656Z otomi:apply:error Listing releases matching ^nginx-ingress-private$                                                                                                                                               │
│ 2021-08-11T14:12:00.791Z otomi:apply:error Listing releases matching ^operator-lifecycle-manager$                                                                                                                                          │
│ 2021-08-11T14:12:00.908Z otomi:apply:log operator-lifecycle-manager    operator-lifecycle-manager    1
```

**Expected behavior:** (a clear and concise description of what you expected to happen)
Log helmfile logs as info instead of error.

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Comment by Dunky13** [comment] 2021-08-16 07:43
Sadly not a bug. Helmfile pipes these lines to stderr, not stdout. That's why it's printed as error. I could write a test to see if it should print as error or not, but that sounds too convoluted?

**Comment by Morriz** [comment] 2021-08-16 09:37
closing as this is expected behaviour...but please document in otomi.io with some lines @Dunky13

**Closed by Morriz** 2021-08-16 09:37 UTC
Labels: bug
