### ISSUE TITLE
Unable to answer question from otomi cli

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#255] opened 2020-12-16 08:38 UTC
**Describe the bug:** (a clear and concise description of what the bug is)
While performing command in otomi cli, the otomi makes sure that actions are performed on the right cluster and asks a user to confirm switching to the right kubernetes context. Unfortunately it does not parse user answers correctly.

**To Reproduce** Steps to reproduce the behavior:
1. Perform the following shell commands"
```
kubectl config use-context otomi-eks-dev
export CLOUD=aws CLUSTER=dev-1 
otomi diff
Warning: Your current kubernetes context does not match target context: <context-name>. Would you like to switch kube context to target first? Yn
```
2. Answer `Y` 
3. Observe that otomi exists immediately with non-zero exit code.

**Expected behavior:** (a clear and concise description of what you expected to happen)
The otomi cli parses correctly user answers.

Moreover, better formatting and white spaces after question, so
```
Would you like to switch kube context to target first? [Yn] Y
```

Instead of:
```
Would you like to switch kube context to target first? YnY
```
**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**
 - Cloud: aws
 - Cluster: dev

**Versions:** (seen in console's `/settings`)
 - Core Version 0.11.53

**Comment by Morriz** [comment] 2020-12-16 08:50
You report in observation step 3 that it exits with non zero exit code after giving false input, which is correct. Can you please rephrase what is going on? As I see this now this is intented behaviour and I will have to close this if you can't provide clearly what the problem is.

**Comment by j-zimnowoda** [comment] 2020-12-16 12:11
@Morriz, Apparently, it is not clear what is the right input.
Is `Y` an incorrect input, if so then there should be an error printed.

**Comment by Morriz** [comment] 2020-12-23 17:34
It is standard behaviour to offer the default value in capital, closing

**Closed by Morriz** 2020-12-23 17:34 UTC
Labels: bug

**Comment by svatwork** [comment] 2020-12-24 07:32
I think @j-zimnowoda also was confused about the formatting here, it can be improved. Ie.:

`YnY` to `[Yn] Y]` where `Y` is what the user put in. At the moment there is no spacing between Yn and Y.

**Comment by Morriz** [comment] 2020-12-24 10:59
Look, just do what others do, and add the brackets then:

[Yn]
